"""
This script takes reported fixes from clang-tidy and applies them.

This is basically a replacement for the standard clang-apply-replacements tool,
except that it doesn't suck. Instead of doing brittle and arcane directory traversals
in search of compile commands and clang-tidy fixes like clang-apply-replacements does,
it takes a path to a specific yaml file containing the fixes you
want to apply. And it contains a number of other useful options.

This script can be invoked directly or through `bazel run`.

- Arguments:
  -f,--fixes: Path to the yaml file containing clang-tidy fixes (default: clang_tidy_fixes.yaml).
  -y,--yes: Run in non-interactive mode. In the default interactive mode, each fix must be
            confirmed (enter or type 'y'), and if any fixes conflict with each other (overlap),
            the user is prompted to make a choice. In non-interactive mode, all fixes are
            applied and only the first of any set of conflicting fixes is applied.
  -d,--dry-run: Run through without writing out the changes to the files.
  --exclude-paths: A regex applied to file paths, if it matches, those files are not fixed
                   (default: "external/"). If it's an empty string, it will match nothing.
  --include-paths: A regex applied to file paths, if it matches, those files are fixed, unless
                   they match the `--exclude-paths` pattern (default: ".*").
  --exclude-checks: A regex applied to checks, checks matching this pattern won't be fixed 
                    (default: "modernize-use-ranges" (because it breaks the code by leaving
                    stray commas)). If it's an empty string, it will match nothing.
  --include-checks: A regex applied to checks, checks matching this pattern will be fixed, unless
                    they match the `--exclude-checks` pattern (default: ".*").
  trailing positional arguments: A list of files to fix, if none, then fix everything.

"""

import argparse
import os
import pathlib
import re
import sys
from cc_meta.yaml_wrapper import yaml_safe_load_all


def _load_yaml_or_empty_list(filename):
    result = []
    if filename:
        with open(filename, "r", encoding="utf-8") as f:
            result = list(yaml_safe_load_all(f))
    if not result:
        return []
    return result


def _print_replacement(rep: dict, original_text: str):
    rep_check = rep["Parent"]["DiagnosticName"]
    rep_message = rep["Parent"]["DiagnosticMessage"]["Message"]
    rep_offset = rep["Offset"]
    rep_length = rep["Length"]
    print(f"[{rep_check}] {rep_message}")
    prior_nl = max(0, original_text.rfind(b"\n", 0, rep_offset) + 1)
    next_nl = original_text.find(b"\n", rep_offset)
    next_nl = next_nl if next_nl >= 0 else len(original_text)
    print("At: {}".format(original_text[prior_nl:next_nl].decode("utf-8")))
    print("    {}{}".format(" " * (rep_offset - prior_nl), "^" * max(1, rep_length)))
    print("   {}'{}'".format(" " * (rep_offset - prior_nl), rep["ReplacementText"]))


def _ensure_cwd_is_workspace_root():
    """Set the current working directory to the root of the workspace."""
    # The `bazel run` command sets `BUILD_WORKSPACE_DIRECTORY` to "the root of the workspace
    # where the build was run." See: https://bazel.build/docs/user-manual#running-executables.
    try:
        workspace_root = pathlib.Path(os.environ["BUILD_WORKSPACE_DIRECTORY"])
    except KeyError:
        return
    # Change the working directory to the workspace root (assumed by future commands).
    # Although this can fail (OSError/FileNotFoundError/PermissionError/NotADirectoryError),
    # there's no easy way to recover, so we'll happily crash.
    os.chdir(workspace_root)


def main():
    parser = argparse.ArgumentParser(
        prog="ApplyClangTidyFixes",
        description="Apply clang-tidy exported fixes. Basically, like "
        + "clang-apply-replacements, but usable.",
    )
    parser.add_argument(
        "-f",
        "--fixes",
        default="clang_tidy_fixes.yaml",
        help="Path to the yaml file generated by clang-tidy or a derived tool.",
    )
    parser.add_argument(
        "-y",
        "--yes",
        action="store_true",
        help="Non-interactive mode, yes to everything.",
    )
    parser.add_argument(
        "-d",
        "--dry-run",
        action="store_true",
        help="Do a dry-run, don't write out changes to files.",
    )
    parser.add_argument(
        "--exclude-paths",
        default="external/",
        help="A regex pattern for which matching file paths will be skipped.",
    )
    parser.add_argument(
        "--include-paths",
        default=".*",
        help="A regex pattern for which matching file paths will be fixed "
        + "(unless excluded by --exclude-paths).",
    )
    parser.add_argument(
        "--exclude-checks",
        default="modernize-use-ranges",
        help="A regex pattern for which matching clang-tidy check will not be fixed.",
    )
    parser.add_argument(
        "--include-checks",
        default=".*",
        help="A regex pattern for which matching clang-tidy check will be fixed "
        + "(unless excluded by --exclude-checks).",
    )
    parser.add_argument(
        "file_list",
        nargs="*",
        help="List of specific files to fix. If empty, fix all files in the report.",
    )
    args = parser.parse_args()

    _ensure_cwd_is_workspace_root()

    incl_paths = re.compile(args.include_paths)
    excl_paths = re.compile(args.exclude_paths if args.exclude_paths else "(?!)")
    incl_checks = re.compile(args.include_checks)
    excl_checks = re.compile(args.exclude_checks if args.exclude_checks else "(?!)")

    files_to_fix = set()
    if args.file_list:
        for fpath in args.file_list:
            if not incl_paths.search(fpath) or excl_paths.search(fpath):
                continue
            if not os.path.exists(fpath):
                print(
                    "ERROR: File {} does not exist! Skipping...".format(fpath),
                    file=sys.stderr,
                )
                continue
            files_to_fix.update(fpath)

    raw_tidy_issues = _load_yaml_or_empty_list(args.fixes)
    seen_diags = set()
    # Flatten and fix the tidy diagnostics, we don't need the main-source-file breakdown.
    flat_tidy_issues = []
    for tidy_mainfile in raw_tidy_issues:
        if (not tidy_mainfile) or ("Diagnostics" not in tidy_mainfile):
            continue
        new_tidy_diags = []
        for diag in tidy_mainfile["Diagnostics"]:
            diag_msg = diag["DiagnosticMessage"]
            if "Replacements" not in diag_msg or not diag_msg["Replacements"]:
                # Skip diagnostics without fix suggestions
                continue
            diag_msg["FilePath"] = diag_msg["FilePath"].removeprefix("./")
            primary_path = diag_msg["FilePath"]
            if not incl_paths.search(primary_path) or excl_paths.search(primary_path):
                # Skip diagnostics for excluded files
                continue
            rule_name = diag.get("DiagnosticName", "unknown-check")
            if not incl_checks.search(rule_name) or excl_checks.search(rule_name):
                # Skip diagnostics for excluded checks
                continue
            for rep in diag_msg["Replacements"]:
                if "FilePath" in rep:
                    rep["FilePath"] = rep["FilePath"].removeprefix("./")
            primary_loc = diag_msg.get("FileOffset", 0)
            diag_id = f"{rule_name}:{primary_path}:{primary_loc}"
            if diag_id not in seen_diags:
                new_tidy_diags.append(diag)
                seen_diags.add(diag_id)
        flat_tidy_issues += new_tidy_diags

    replacements_list = [
        (rep | {"Parent": ti, "Active": True})
        for ti in flat_tidy_issues
        for rep in ti["DiagnosticMessage"]["Replacements"]
    ]
    sorted_replacements = sorted(
        replacements_list, key=lambda x: (x["FilePath"], x["Offset"])
    )

    current_file = {"path": "", "content": bytes(), "output": bytes(), "i": 0}
    fixes_applied = 0
    files_fixed = 0

    def flush_current_output():
        nonlocal current_file, files_fixed
        if not current_file["content"] or current_file["i"] == 0:
            return
        files_fixed += 1
        current_file["output"] += current_file["content"][current_file["i"] :]
        if args.dry_run:
            return
        with open(current_file["path"], "wb") as out_file:
            out_file.write(current_file["output"])

    def load_new_file(fpath):
        nonlocal current_file
        current_file["path"] = fpath
        with open(current_file["path"], "rb") as in_file:
            current_file["content"] = in_file.read()
        current_file["i"] = 0
        current_file["output"] = bytes()

    def fastforward_to_next_file(next_i, current_path):
        # Advance to next file or end
        next_i += 1
        while next_i < len(sorted_replacements):
            if current_path != sorted_replacements[next_i]["FilePath"]:
                break
            next_i += 1
        return next_i

    rep_i = 0
    while rep_i < len(sorted_replacements):
        rep = sorted_replacements[rep_i]
        if not rep["Active"]:
            rep_i += 1
            continue
        # Detect a new file.
        if current_file["path"] != rep["FilePath"]:
            if files_to_fix and rep["FilePath"] not in files_to_fix:
                rep_i = fastforward_to_next_file(rep_i, rep["FilePath"])
                continue
            flush_current_output()
            load_new_file(rep["FilePath"])
            if not args.yes:
                print("==================================================")
            print("===== Fixing file '{}'".format(current_file["path"]))
            if not args.yes:
                print("==================================================")
        # Check for conflicts with next replacements
        rep_offset = rep["Offset"]
        if rep_offset < current_file["i"]:
            print(
                f"ERROR: Next fix is at offset {rep_offset}, but we've already moved beyond "
                + "that point! That should never happen! Skipping...",
                file=sys.stderr,
            )
            rep_i += 1
            continue
        rep_length = rep["Length"]
        conflict_set = []
        for rep_ni in range(rep_i + 1, len(sorted_replacements)):
            rep_n = sorted_replacements[rep_ni]
            # Already suppressed.
            if not rep_n["Active"]:
                continue
            # Moved on to another file.
            if rep_n["FilePath"] != current_file["path"]:
                break
            # Moved past the current fix's range.
            if rep_n["Offset"] >= rep_offset + rep_length:
                break
            # If non-interactive, arbitrarily accept first replacement.
            if args.yes:
                rep_n["Active"] = False
                break
            # Add to conflict set
            conflict_set.append(rep_ni)

        # Resolve conflicts
        if conflict_set:
            conflict_set.insert(0, rep_i)
            print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print("Conflicting fixes! Please choose one of the following fixes:")
            for c_i, c_rep_i in enumerate(conflict_set):
                print(f"{c_i + 1}:")
                _print_replacement(
                    sorted_replacements[c_rep_i], current_file["content"]
                )
            kept_fix = (
                input(
                    "Please choose (0: skip all; s: skip all and the rest of this file) "
                    + "(default: 1): "
                )
                .strip()
                .lower()
            )
            print("------------------------------------------------------------")
            if not kept_fix:
                kept_fix = 1
            elif kept_fix == "s":
                kept_fix = -1
            else:
                kept_fix = int(kept_fix)
            # Deactivate skipped fixes
            for c_i, c_rep_i in enumerate(conflict_set):
                if kept_fix != c_i + 1:
                    sorted_replacements[c_rep_i]["Active"] = False
            if kept_fix < 0:
                # Skip all fixes remaining in this file
                rep_i = fastforward_to_next_file(rep_i, current_file["path"])
                continue
            if kept_fix == 0:
                # Skip all conflicting fixes
                rep_i = conflict_set[-1]
                rep_i += 1
                continue
            # Skip to chosen fix and start the loop again (in case it conflicts with other fixes)
            rep_i = conflict_set[kept_fix - 1]
            continue

        # Ask user if the replacement should be applied
        if not args.yes:
            print(">>> Applying the following fix:")
            _print_replacement(rep, current_file["content"])
            kept_fix = (
                input(
                    "Please choose (y or n; s: skip it and the rest of this file) (default: y): "
                )
                .strip()
                .lower()
            )
            if not kept_fix:
                kept_fix = "y"
            if kept_fix == "s":
                # Skip all fixes remaining in this file
                rep_i = fastforward_to_next_file(rep_i, current_file["path"])
                continue
            if kept_fix != "y":
                rep["Active"] = False
                rep_i += 1
                continue

        # Apply the replacement
        current_file["output"] += current_file["content"][
            current_file["i"] : rep_offset
        ]
        current_file["i"] = rep_offset + rep_length
        current_file["output"] += rep["ReplacementText"].encode("utf-8")
        fixes_applied += 1
        if not args.yes:
            print("<<< Fix applied!")
        # Move on to the next fix
        rep_i += 1

    flush_current_output()

    print(">>> Applied {} fixes in {} files.".format(fixes_applied, files_fixed))


if __name__ == "__main__":
    main()
